backend:
  name: github
  repo: morgansegura/ether-starter
  branch: master
publish_mode: editorial_workflow
media_folder: static/images
public_folder: images

display_url: https://google.com

collections:
  # Settings Section
  - name: 'settings'
    label: 'Site Settings'
    slug: '{{slug}}'
    files:
      # Site Settings (Logo and Menu)
      - file: 'src/pages/settings/index.md'
        label: 'General Settings'
        name: 'settings-index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'settings',
            }
          - {
              label: 'Show Splash Page',
              name: 'home-or-spash',
              widget: 'boolean',
              hint: 'If unchecked the home page will shown in place of the splash page.',
              default: false,
            }
          - {
              label: 'Override Metadata',
              name: 'meta',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Title',
                    name: 'title',
                    widget: 'string',
                    hint: 'This title will be displayed in the <head> of your website.',
                  },
                  {
                    label: 'Meta Keywords',
                    name: 'keywords',
                    widget: 'string',
                    hint: 'Create strong meta keywords for your main page.',
                  },
                  {
                    label: 'Meta Description',
                    name: 'description',
                    widget: 'string',
                    hint: 'Create a good meta description for your main page.',
                  },
                ],
            }

      # Menus
      - file: 'src/pages/settings/menus.md'
        label: 'Menu Settings'
        name: 'settings-menus'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'settings',
            }
          - {
              label: 'Header Menu',
              name: 'menuHeader',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Main Menu',
                    name: 'mainMenu',
                    widget: 'list',
                    fields:
                      [
                        {
                          label: 'Label',
                          name: 'label',
                          widget: 'string',
                          hint: 'The visible text in this link.',
                        },
                        {
                          label: 'Link Type',
                          name: 'linkType',
                          widget: 'select',
                          options: ['internal', 'external'],
                          hint: 'Choose between internal and external.',
                        },
                        {
                          label: 'Link URL',
                          name: 'linkURL',
                          widget: 'string',
                          hint: 'Use a relative URL (e.g. /about) if the link is an internal link. Otherwise, (e.g. https://google.com)',
                        },
                      ],
                  },
                  {
                    label: 'Account Menu',
                    name: 'accountMenu',
                    widget: 'list',
                    fields:
                      [
                        {
                          label: 'Icon Class',
                          name: 'icon',
                          widget: 'string',
                          hint: 'Add the appropriate class.',
                        },
                        {
                          label: 'Label',
                          name: 'label',
                          widget: 'string',
                          hint: 'The visible text in this link.',
                        },
                        {
                          label: 'Link Type',
                          name: 'linkType',
                          widget: 'select',
                          options: ['internal', 'external'],
                          hint: 'Choose between internal and external.',
                        },
                        {
                          label: 'Link URL',
                          name: 'linkURL',
                          widget: 'string',
                          hint: 'Use a relative URL (e.g. /about) if the link is an internal link. Otherwise, (e.g. https://google.com)',
                        },
                      ],
                  },
                ],
            }

      # Header Settings
      - file: 'src/pages/settings/header.md'
        label: 'Header Settings'
        name: 'settings-header'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'settings',
            }
          - {
              label: 'Logo',
              name: 'logo',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Image',
                    name: 'image',
                    widget: 'image',
                    hint: 'Upload an image. Leave blank to display text.',
                  },
                  {
                    label: 'Image Description',
                    name: 'alt',
                    widget: 'string',
                    hint: '(SEO) The Alt tage for this image.',
                  },
                ],
            }
          - {
              label: 'Header Settings',
              name: 'header',
              widget: 'object',
              required: false,
              fields:
                [
                  {
                    label: 'Background Color',
                    name: 'bgColor',
                    widget: 'color',
                    presets: ['red', 'green', 'blue'],
                    default: 'white',
                    hint: 'Adjust the background-color of the <footer> area.',
                  },
                  {
                    label: 'Text Color',
                    name: 'textColor',
                    widget: 'color',
                    presets: ['red', 'green', 'blue'],
                    default: 'black',
                    hint: 'Adjust the font color.',
                  },
                  {
                    label: 'Link Color',
                    name: 'linkColor',
                    widget: 'color',
                    presets: ['red', 'green', 'blue'],
                    default: 'blue',
                    hint: 'Adjust the link color.',
                  },
                  {
                    label: 'Link Hover Color',
                    name: 'linkHoverColor',
                    widget: 'color',
                    presets: ['red', 'green', 'blue'],
                    default: 'teal',
                    hint: 'Adjust the link color.',
                  },
                ],
            }

      # Footer Settings
      - file: 'src/pages/settings/footer.md'
        label: 'Footer Settings'
        name: 'settings-footer'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'settings',
            }
          - {
              label: 'Background Color',
              name: 'bgColor',
              widget: 'color',
              presets: ['red', 'green', 'blue'],
              default: 'white',
              hint: 'Adjust the background-color of the <footer> area.',
            }
          - {
              label: 'Text Color',
              name: 'textColor',
              widget: 'color',
              presets: ['red', 'green', 'blue'],
              default: 'black',
              hint: 'Adjust the font color.',
            }
          - {
              label: 'Link Color',
              name: 'linkColor',
              widget: 'color',
              presets: ['red', 'green', 'blue'],
              default: 'blue',
              hint: 'Adjust the link color.',
            }
          - {
              label: 'Link Hover Color',
              name: 'linkHoverColor',
              widget: 'color',
              presets: ['red', 'green', 'blue'],
              default: 'teal',
              hint: 'Adjust the link color.',
            }

  - name: 'post'
    label: 'Post'
    folder: 'src/pages/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'page'
    label: 'Page'
    folder: 'src/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'page',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'home'
    label: 'Home Page'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Tags', name: 'tags', widget: 'list' }
