backend:
  name: github
  repo: morgansegura/ether-starter
  branch: master
publish_mode: editorial_workflow
media_folder: ./static/images
public_folder: images

display_url: https://google.com

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/pages/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'page'
    label: 'Page'
    folder: 'src/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'page',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
  # Create Theme Pages
  # - name: 'static'
  #   label: 'Prebuilt Pages'
  #   files:
  #     - file: 'src/pages/home/index.md'
  #       label: 'Home'
  #       name: 'home'
  #       fields:
  #         - {
  #             label: 'Template Key',
  #             name: 'templateKey',
  #             widget: 'hidden',
  #             default: 'home-page',
  #           }
  #         - { label: 'Title', name: 'title', widget: 'string' }
  #         - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #         - { label: 'Description', name: 'description', widget: 'text' }
  #         - { label: 'Body', name: 'body', widget: 'markdown' }
  #         - { label: 'Tags', name: 'tags', widget: 'list' }
