backend:
  name: github
  repo: morgansegura/catapultarts
  branch: master
publish_mode: editorial_workflow
media_folder: static/images
public_folder: images

display_url: https://google.com

collections:
  - name: 'post'
    label: 'Blog'
    folder: 'src/pages/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  # Create Theme Pages
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - {
              label: 'SEO & Meta ',
              name: 'seo',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Browser Tab Title',
                    name: 'browserTitle',
                    widget: 'string',
                  },
                  {
                    label: 'Keywords',
                    name: 'title',
                    widget: 'string',
                    hint: 'SEO keywords for the Home Page.',
                  },
                  {
                    label: 'Description',
                    name: 'description',
                    widget: 'text',
                    hint: 'SEO description for the Home Page.',
                  },
                  {
                    label: 'External Scripts',
                    name: 'meta',
                    widget: 'list',
                    hint: 'Scripts will be added before the </body> of your website. For Help: https://catapultarts.com/docs/adding-scripts',
                    fields:
                      [
                        {
                          label: 'Script',
                          name: 'src',
                          widget: 'string',
                          hint: 'Add only the link to the script. e.g. https://src-to-cdn.com ',
                        },
                      ],
                  },
                ],
            }
