backend:
  name: github
  repo: morgansegura/ether-starter
  branch: master
  accept_roles:
    - admin
    - editor  
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: Featured Image, name: featuredImage, widget: object,
          fields: [
            {label: Image, name: image, widget: image},
            {label: Alt, name: alt, widget: string}
          ]
        }      
      - {label: Image Gallery, name: gallery, widget: list, 
          fields: [
            {label: Image, name: image, widget: image},
            {label: Alt, name: alt, widget: string}
          ]
        }    
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "shop"
    label: "Shop Item"
    folder: "src/pages/shop"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "shop-item"}
      - {label: "Item Publish Date", name: "date", widget: "datetime"}      
      - {label: "Item Title", name: "title", widget: "string"}
      - {label: Item Description, name: description, widget: text}
      - {label: Item Price, name: price, widget: number, default: 0, valueType: float}
      - {label: Items in stock, name: inStock, widget: number, default: 0, valueType: int}
      - {label: Item Discounted Price, name: discount, widget: number, default: 0, valueType: float}
      - {label: Item Main Image, name: mainImage, widget: object,
          fields: [
            {label: Image, name: image, widget: image},
            {label: Alt, name: alt, widget: string}
          ]
        }
      - {label: Item Gallery, name: gallery, widget: list, 
          fields: [
            {label: Image, name: image, widget: image},
            {label: Alt, name: alt, widget: string}
          ]
        }
         
      - {label: Details, name: details, widget: object,
          fields: [
            {label: More, name: more, widget: list,
              fields: [
                {label: New Item Label, name: label, widget: string, default: none},
                {label: New Item Option, name: item, widget: string, default: none}
              ]
            },
          ]
        }
         
      - {label: Color - Hex grid (https://htmlcolorcodes.com/), name: color, widget: object,                      
          fields: [
            {label: Layout, name: style, widget: select, default: radioList,
              options: [
                {label: Radio Button List, value: radioList},
                {label: Select Menu List, value: selectList}             
              ]
            },
            {label: New Color, name: color, widget: list,
              fields: [
                {label: Color, name: color, widget: string},
                {label: Hex Color (optional - ex.`#ffffff`), name: hex, widget: string}
              ]                
            }
          ]
        }
      - {label: Size, name: size, widget: object,                      
          fields: [
            {label: Layout, name: style, widget: select, default: radioList,
              options: [
                {label: Radio Button List, value: radioList},
                {label: Select Menu List, value: selectList}           
              ]
            },    
            {label: New Size, name: size, widget: list,
              fields: [
                {label: Size, name: size, widget: string},
                {label: Short Name (optional - ex.SM), name: short, widget: string},
                {label: Amount (total in stock), name: amount, widget: number, valueType: int}
              ]                
            }
          ]
        }

  - name: "pages"
    label: "Pages"
    create: true
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/pricing/index.md"
        label: "Pricing Page"
        name: "pricing"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pricing-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}